# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "bento/debian-11.4"
	config.vm.box_version = "202207.19.0"

  config.vm.network "forwarded_port", guest: 8001, host: 8001
  config.vm.network "forwarded_port", guest: 8002, host: 8002
  config.vm.network "forwarded_port", guest: 8003, host: 8003
  config.vm.network "forwarded_port", guest: 9201, host: 9201

  config.vm.provider "virtualbox" do |vb|
    vb.name = "odr-mmbtools"
    vb.customize ['modifyvm', :id, '--usbxhci', 'on']
  end
end
  