# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
	apt-get update
	apt-get install -y git
	git clone \
		--branch next \
		https://github.com/opendigitalradio/dab-scripts.git \
		/home/vagrant/dab-scripts
	bash /home/vagrant/dab-scripts/install/mmbtools-get \
		--branch next \
		--odr-user odr \
		install
	SCRIPT

Vagrant.configure("2") do |config|
	config.vm.box = "debian/bullseye64"
	config.vm.define "mmbtools"

	config.vm.network "forwarded_port", guest: 8001, host: 8001
	config.vm.network "forwarded_port", guest: 8002, host: 8002
	config.vm.network "forwarded_port", guest: 8003, host: 8003
	config.vm.network "forwarded_port", guest: 9201, host: 9201

	config.vm.provider "virtualbox" do |vb|
		vb.cpus = 2
		vb.memory = 2048
		vb.customize ['modifyvm', :id, '--usbxhci', 'on']
	end

	config.vm.provider :libvirt do |libvirt|
		libvirt.cpus = 2
		libvirt.memory = 2048
		libvirt.usb_controller :model => "qemu-xhci"
		libvirt.usb :vendor => '0x1d50', :product => '0x6089'
	end

	config.vm.provision "shell" do |s|
		s.privileged = true
		s.env = {"DEBIAN_FRONTEND" => "noninteractive"}
		s.inline = $script
	end

end
